### ISSUE TITLE
大佬可否出一个部署的教程，看着这里的描述真的运行不起来

### ISSUE THREAD

**Issue by Wyatt323** [ThekingMX1998/MyUrls#1]

**Comment by ThekingMX1998** [comment]
[Usage](https://github.com/ThekingMX1998/MyUrls#usage) 部分说的已经比较详细了 也可以选择用docker 或部署再[railway](https://github.com/ThekingMX1998/MyUrls#deploy-on-railway) 上

**Comment by Wyatt323** [comment]
我是docker部署的，docker和docker compose都试过了，docker+本地redies能监听到redies的端口，但是myurl打不开；用docker-compose部署能打开urls，但是redies监听不到端口，导致获取短链接失败

**Comment by ThekingMX1998** [comment]
docker部署你是否配置好了 **.env** 文件

**Comment by Wyatt323** [comment]
该配置的都配置了，就是不知道问题出在哪里

**Comment by ThekingMX1998** [comment]
那到时候我出一个更简单的教程

**Comment by Wyatt323** [comment]
感谢大佬
